version: '3.7'

services:
  mongo:
    image: mongo:3.6.18
    environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sample-db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
